import Foundation

// placeholders until we get to them
// TODO(markd, 11/19/2018) use longer names.  abbrvs sk.
protocol SymTab: class { } 
protocol ICode: class { }
protocol Token: class { }

/// Language-indendent.
protocol Parser: class {

    // TODO(markd, 11/19/2018) - does this need to be in Parser's public interface?
    // Dependency-inject them?
    var symTab: SymTab? {get set} // generated symbol table

    var scanner: Scanner? {get set} // scanner used for this parser
    var iCode: ICode? {get set}     // intermediate code generated by this parser

    init(scanner: Scanner)

    /// Parse a source program and generate the intermediate code and the
    /// symbol table.
    func parse() throws

   /// Return the number of syntax errors found by the parser.
      func getErrorCount()

    func currentToken() -> Token
    func nextToken() throws -> Token
}

